### ISSUE TITLE
Corporate Console - Empty table with no data is displayed when all the Pending CLA Manager requests are accepted/declined

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1065]
## Background
**Preqreuisite**
All the Pending CLA Manager requests for the project should be accepted /declined

**Steps to Follow**
1. Launch Corporate console
2. Login as CLA Manager
3. Click on the Company
4. Click on the project
5. Observed that Empty table with no data is displayed. 
![image](https://user-images.githubusercontent.com/60865903/81148333-b94fbb80-8f99-11ea-8852-ad160d85e1e2.png)

**Initial behavior when there are no CLA Manager requests**
![image](https://user-images.githubusercontent.com/60865903/81148375-cb315e80-8f99-11ea-8b43-fa466272768f.png)

**Comment by amolsontakke3576** [comment]
it looks like issue is fixed 
![Screenshot from 2020-09-07 12-47-27.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/08d0c01c-e857-49b5-97fd-757779864e13)

**Comment by nirupamav** [comment]
Issue is still reproducible. 
Accept CLA Manager request and observed that empty table is displayed
**Before**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a5e4ea96-2e81-42f4-b7dd-796a451056ce)

**After**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/95e39d1d-ad32-4cb8-9844-1b511cf8f177)

**Comment by dealako** [comment]
Old console is deprecated and removed.
