### ISSUE TITLE
API v2 - Approval List

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1135]
## Summary

Implement v2 API Approval List to allow the LFX UI to add/remove users from the email, domain, GH Username, GH Org approval lists.

## Background

Provide v2 functionality of the Approval lists.

## User Story

As a v2 CLA Manager, I want to edit the approval list.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
Status: API Complete

API-DOCS: https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/updateApprovalList

API Example:

PUT: http://localhost:8080/v4/signatures/project/a0941000005ouJFAAY/company/external-ee965ea2-ca83-4482-8a1b-94a468d9dcfa/clagroup/d5412846-5dda-4c58-8f62-4c111a3cd0d3/approval-list

where inputs:

Project SF ID

Org SF ID

CLA Group ID

Payload Example:

{
"AddEmailApprovalList": ["ahmed@foo.com"],
"RemoveEmailApprovalList": ["user@bar.com", "bryan@linuxfoundation.org"],
"AddDomainApprovalList": ["google.com", "googleinc.com"],
"RemoveDomainApprovalList": [],
"AddGithubUsernameApprovalList": [],
"RemoveGithubUsernameApprovalList": [],
"AddGithubOrgApprovalList": [],
"RemoveGithubOrgApprovalList": []
}

All the above items are optional.

**Comment by dealako** [comment]
Currently working on CLA Manager role permissions problem.

**Comment by dealako** [comment]
@nirupamav resolved several issues:
- got all the functional tests working for CLA Manager Update Approval list
- resolved email bulleted list issue
- Changed 401 to 403 when not authorized

**Comment by nirupamav** [comment]
Queries and Issues
1. Should admin and userExternalID fields be returned in the response. These fields are available in response model mentioned in the api docs
2. Observed that all fields accept only spaces. Also email and domain field accepts any free text. There is no validation for the fields
3. Observed that able to post with empty object and below is how the email looks
**payload**
{
}
**Email**
![image](https://user-images.githubusercontent.com/60865903/83266756-e2521d80-a1e0-11ea-9cb1-7d91b7fd9229.png)

4. A cosmetic issue. There is an empty bullet in the email content
![image](https://user-images.githubusercontent.com/60865903/83266632-b9318d00-a1e0-11ea-93ce-41e31111f75d.png)
5. Observed that 403 is returned when user does not have access to the project in IAM, Other endpoints return 401. Not sure which is the expected behavior

**Comment by dealako** [comment]
I will create a PR to address the above:

1. Will review the response model
1. I will have to consider how much validation we want to add.  I guess we can fail early/hard on bad data.
1. Will trap for empty payload and return BadRequest
1. Email - darn email formatting. I will resolve it.
1. @niravpatel27 has mentioned I should return 403

**Comment by dealako** [comment]
@nirupamav  I have pushed an update that should address the above issues.

1. The response model - still need to review - maybe user data is missing in our DB
1. Added a bunch of validation - we can discuss it. See [email](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/utils/utils.go#L151), [domain](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/utils/utils.go#L157), [GH User](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/utils/utils.go#L213), [GH Org](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/utils/utils.go#L230) - let's change if you feel this is not adequate.  I've [added additional functional testing](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/cmd/functional_tests/approval_list/approval_list.go#L894-L903) for validation.
1. Added test
1. Resolved email.
1. Works as designed - should return 403.  We need to update other APIs to do the same.

**Comment by nirupamav** [comment]
**_Tested and observed that below issues are still reporoducible_**
2. Observed that error message is displayed now. However observed below issues
- Even if other fields have issues only issue for email is displayed in response. Also observed that error message is displayed only for the first value in email. After fixing the issue with email field, error message for domain is displayed. Error details for all fields with error are not displayed
![image](https://user-images.githubusercontent.com/60865903/83387657-b74b1200-a40a-11ea-82e9-f9f25418d8be.png)
- Below invalid values are accepted from API but in UI these values are not accepted
![image](https://user-images.githubusercontent.com/60865903/83387719-dd70b200-a40a-11ea-9cb6-8a90bce6c52b.png)

**New Issues which I had missed to report last time**
6. When duplicate data is added, 200 is returned and functionally only one value is added to database, but in email duplicate entries are shown
![image](https://user-images.githubusercontent.com/60865903/83388323-e0b86d80-a40b-11ea-932e-540b32dc5919.png)
7. When trying to add already existing data, 200 is returned and functionally only one value exists in database, but in email the value is shown as added. Should 400 be returned in this scenario saying value already exists?
**In UI**
![image](https://user-images.githubusercontent.com/60865903/83388864-d2b71c80-a40c-11ea-961a-23f106f6551d.png)
**In Email after trying to add above existing values**
![image](https://user-images.githubusercontent.com/60865903/83388968-06924200-a40d-11ea-9927-93166eb0ad5e.png)
8. Tried to remove the values that does not exist for the CLA group and observed that 200 is returned and email is sent with removed values. Should 400 be returned in this scenario saying value does not exist?
**Payload**
![image](https://user-images.githubusercontent.com/60865903/83389142-56710900-a40d-11ea-9659-704e602c5d3c.png)
**Email content**
![image](https://user-images.githubusercontent.com/60865903/83389185-6ab50600-a40d-11ea-9e9a-bc304292e371.png)



**Below are fixed issues**
3. **400 is returned when empty object is passed in the payload**
![image](https://user-images.githubusercontent.com/60865903/83386319-794cee80-a408-11ea-83cd-1a7c370fd8b1.png)
4. Empty bullet is not displayed in the email content
![image](https://user-images.githubusercontent.com/60865903/83388137-8d461f80-a40b-11ea-9c34-519ab1a5ff7e.png)

**Comment by dealako** [comment]
Regarding:
- Issue 2 above - this is fine for now.  The API protects invalid input data and respond accordingly.  Low priority is to enumerate all the bad things the client is sending us and spell it out for them.
- Issue 2 above for GH Org/GH username - I couldn't find a spec for GH Org/Username.  What reference spec is the UI team using or did they just make up some rules?
- Issue 2 above for Domain - I found a common spec for domain name validation.  What reference spec is the UI team using or did they just make up some rules?  I am using domain name length > 0 and <= 255 characters, can't begin or end with a hyphen, valid ASCII char, can't being with a period.  I'm not going to change unless I see a common spec.
- Issue 6 - API does the correct thing, just the email shows ups. Not a big issue. UI will handle this case and the API does the right thing.  Very low priority fix.
- Issue 7 - API does the correct thing, doesn't add duplicates.  The API gets your point and isn't super picky/opinionated. This is how we designed it.
- Issue 8 - API does the correct thing, doesn't attempt to remove non-existent entries.  The API gets your point and isn't super picky/opinionated. This is how we designed it.

**Comment by nirupamav** [comment]
@dealako 
For Issue 2 regarding the field lengths, I referred to V1 Corporate Console - Manage Approved List UI. However I have posted commented in LFX PRD about the specifications. So should the validations for fields be handled at UI level and not at API level? If you could confirm this then I will skip these validations for other endpoints as well

**Comment by nirupamav** [comment]
Keeping the ticket open due to below issue
#1292 - Initial CLA Manager who signed CLA and CLA Managers added from LFX portal are not able to add approval list from API.

**Comment by nirupamav** [comment]
@pranab-bajpai 
Testing is completed. Could you please review and let me know if I missed and test cases
https://confluence.linuxfoundation.org/display/PROD/approval-list
