### ISSUE TITLE
Authenticated CLA Manager Unable to Edit Approval List

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1582]
## Summary

Authenticated CLA Manager Unable to Edit Approval List

## Background

This issue was reported by @WillsonHG - the situation occurs when a user has multiple email address and we only compare the primary email address stored in the EasyCLA user account - the alternative email address are not reviewed/compared against the authenticated user's auth0 email address.

## Expected behavior

A user who is a CLA manager should be able to edit the approval lists.

## Screenshots

An authenticated user with CLA Manager permissions unable to edit the approval list:

![image (2).png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/cd065cc4-10b2-49bc-80d1-115667a59176)

## Environment

Please complete the following information:

* Environment: STAGING and PROD 
* OS: \[e.g. iOS\]
* Browser \[e.g. chrome, safari\]
* Version \[e.g. 22\]

## Assumptions

If you are assuming certain facts or scenarios, list them so we have a baseline to understand your request.

- [...] Assumption 1
- [...] Assumption 2

## Questions

List any questions or clarifications that are needed to addressed to satisfy this request.

1. [...] Question 1...
1. [...] Question 2...

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
Updating response to load alternative emails, such as:

```[
    {
        "name": "Foo Bar",
        "email": "foo@spirent.com",
        "alt_emails": [
            "foo@gmail.com",
            "foo@spirent.com"
        ],
        "github_user_id": null,
        "github_username": null,
        "lfid": "foo"
    }
]

**Comment by nirupamav** [comment]
**Issue is still reproducible. Below are the steps that I tried**

1. Request CLA Manager access to a project and request us accepted
2. Add approved list for the project
3. Now change the primary email of the CLA Manager
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/521bbbc5-932b-42f8-bfdd-0669038eb6b5)
4. Clear cache and relogin to corporate console
5. Now the status REQUEST ACCESS even if the user is CLA Manager for the company. Since the status is REQUEST ACCESS, CLA Manager is not able to Edit approved list
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/92f1ddb8-b2ec-4e8b-9cd5-10a2d9cfa98e)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/aa96ff25-622b-4c7c-a11e-da67b2416583)

**Comment by dealako** [comment]
Currently, we do not receive an event when the user updates their profile in `myprofile` (from user service).

**Comment by dealako** [comment]
Odd - this user has multiple user records:

- `3f9c6f07-c596-11ea-ad6b-5ed17d25e40a`
- `3f9d98cc-c596-11ea-b0db-76d0fcad1637`

Everything is identical except the record create/modified dates and ... the first record has a company_id association.
![Screen Shot 2020-08-20 at 1.42.54 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/abff3852-27f9-4e7a-8b67-aef0c7f91d79)

**Comment by dealako** [comment]
@nirupamav we have merged the changes from @rinkeshbhutwala which provided an API update when users adjust their primary and secondary/alternative email addresses.

See PRs:
- [1890](https://github.com/communitybridge/easycla/pull/1890)
- [1930](https://github.com/communitybridge/easycla/pull/1930)
- [1932](https://github.com/communitybridge/easycla/pull/1932)
- [1945](https://github.com/communitybridge/easycla/pull/1945)
- [1953](https://github.com/communitybridge/easycla/pull/1953)

**Comment by nirupamav** [comment]
**Issue is still reproducible. Tested an observed that after following the steps mentioned above, the status of the user is changed from CLA Manager to Request Access after changing user details**

**Before updating user details**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/172644b8-875c-49f8-837a-2e0a05495a44)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8e6ad116-f9a3-4e19-bce1-036a004b4884)

**After updating user details**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/57fc56a4-4f22-420a-ba0a-19bc656238b5)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b78e5ad7-d0ed-496f-8fdd-9bdefdd8eb51)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/200a0d88-21f2-49fa-a33a-c6cca1bbce91)

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
