### ISSUE TITLE
Generated Template Overwrites Old Template in S3

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1871]
## Summary

Generated Template Overwrites Old Template in S3

## Background

When a set of new CLA templates is generated using the API, the new PDF document "overwrites" the old document in S3.  As a result, we are unable to view the previously generated PDF files.  This task is to implement a backup/renaming strategy.

## Tasks

- [x] Rename old PDF and update CLA Group record URL. Example, rename `icla.pdf` to `icla-YYYY-MM-DDTHH-MM-SS.pdf` or similar strategy
- [x] Ensure version is updated in the CLA Group record

## Expected behavior

New tempaltes should not overwrite existing templates.

## Screenshots

![Screen Shot 2020-09-25 at 11.46.11 AM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/a3bdbcb8-1af6-4693-bb78-5803498f6a5b)

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
Created PR:https://github.com/communitybridge/easycla/compare/master...dealako:bug/1873-ccla-template-not-added-to-doc-list?expand=1

Ready for confirmation/validation.

**Comment by dealako** [comment]
@nirupamav 

Ready for confirmation validation.

How to test:

1. Create a new CLA Group with both CCLA and ICLA, note the Project Name, Entity Name, and email address
1. Upon completion and possible page refresh, observe the dates/times are correct on the project console for the New CLA Group
1. Observe the dates are correct in the ICLA PDF Icon -> Modal pop-up. Observe that there is one PDF for ICLA.
1. Observe the dates are correct in the CCLA PDF Icon -> Modal pop-up. Observe that there is one PDF for CCLA.
1. Find CLA Group in the EasyCLA database - cla-dev-projects
1. Observe that there is one element in the project_individual_documents field and one element is in the project_corporate_documents field.
1. Navigate to AWS S3 DEV - cla-signature-files-dev bucket, path: cla-signature-files-dev/contract-group/{cla_group_id}/template - observe icla and ccla files are in S3 - files have the following format: icla-YYYY-MM-DDTHH-MM-SSZ.pdf and ccla-YYYY-MM-DDTHH-MM-SSZ.pdf format
1. Identify the CLA Group again in the Project console
1. Press the Select Template button, Select Apache Style Template
1. Enter new values, note values you entered, use different values from the previous attempts
1. Generate new templates
1. Upon completion and possible page refresh, observe the dates/times are correct on the project console for the New CLA Group
1. Observe the dates are correct in the ICLA PDF Icon -> Modal pop-up. Observe that there are two PDFs for ICLA. Ensure most recent PDF is first and selected.
1. Observe the dates are correct in the CCLA PDF Icon -> Modal pop-up. Observe that there are two PDFs for CCLA.  Ensure most recent PDF is first and selected.
1. Find CLA Group in the EasyCLA database - cla-dev-projects - may require a new search to "see" updated values.
1. Observe that there are two elements in the project_individual_documents field and two elements are in the project_corporate_documents field.  The first element is the first one added, the second element is the most recent/latest one added.
1. Navigate to AWS S3 DEV - cla-signature-files-dev bucket, path: cla-signature-files-dev/contract-group/{cla_group_id}/template - observe that two icla and two ccla files are in S3 - files have the following format: icla-YYYY-MM-DDTHH-MM-SSZ.pdf and ccla-YYYY-MM-DDTHH-MM-SSZ.pdf format

**Comment by nirupamav** [comment]
**_Tested for New CLA Group/Existing CLA Group and observed issue at step3_**

1. Generated templates and observed that files are generated in below format which is as expected
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c3ce5332-9d45-487a-9f2a-c3a57aa40a1e)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6f2d4d36-9fae-4105-8986-a861bfdc08ae)

2. Generate templates again. Observed that 2 elements exists for project_individual_documents and project_corporate_documents fields
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d6a5c02e-1df1-4863-8f38-7a7a740890db)

3. Observed that recent pdf is selected. However when clicked in PDF icon to view the modal popup, first time generated pdf is selected. If the modal popup is opened again then recently generated pdf is selected. Each time when modal popup is opened, alternatively recently generated and first time generated pdf's are selected. Observed same issue with ICLA pdf as well. If we refresh the page or revisit the page, recently generated file is selected
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b4f2d630-ecca-443b-a0fb-a0ba6104d9b9)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a4d53638-5f5d-4ef2-a031-707cae346e21)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5d3f8081-7f48-46cd-bcc6-9b2fe165b992)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/adb55e0f-c5e5-4cfc-94b9-41a072889b90)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/82bfebf3-947b-4899-a04a-8b38c37208fc)

**Comment by dealako** [comment]
@amolsontakke3576 can you review @nirupamav 's comments above starting with step 3. Is this resolved now with your UI sorting updates?

**Comment by amolsontakke3576** [comment]
@dealako @nirupamav I have verified and it is working as expected.

**Comment by nirupamav** [comment]
**Issue is still reproducible. I am testing in windows10 Chrome. However after refreshing the page latest pdf itself is selected**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/9425d6b2-c8e2-4d06-ab91-8ecc06838370)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a2e45fd9-9688-439e-ad2e-2d764ca7a6f8)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/05fed975-350a-4355-b37b-0ae54cda9857)

**Comment by amolsontakke3576** [comment]
@nirupamav Ohhh now got the issue I will fix it

**Comment by dealako** [comment]
@amolsontakke3576 is this now resolved in the UI?

**Comment by mlehotskylf** [comment]
@amolsontakke3576 is this still relevant, can we close this?

**Comment by mlehotskylf** [comment]
I believe this is for V1, closing.
