### ISSUE TITLE
CLA group creation failed on child parent relationship

### ISSUE THREAD

**Issue by amolsontakke3576** [communitybridge/easycla#3604]

**Comment by nickmango** [comment]
@amolsontakke3576 This has been fixed . @thakurveerendras if you could kindly verify

**Comment by thakurveerendras** [comment]
@amolsontakke3576 , Related PCC ticket [PCC-2622](https://jira.linuxfoundation.org/browse/PCC-2622) for above case is still reproducible.

**Comment by nickmango** [comment]
@thakurveerendras this has been resolved. Kindly verify cc @amolsontakke3576

**Comment by thakurveerendras** [comment]
Related PCC ticket is verified & refer below testing results 

1. Able to create CLA group at foundation, child project & grandchild project
2. Able to create cla group on child/grandchild project when cla group exist at foundation level 
3. GitHub org will associated with added cla group only
