### ISSUE TITLE
CLA Corporate Console Approved List date is not accurate

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#3750]
Ticket: [SUPPORT-12530](https://jira.linuxfoundation.org/browse/SUPPORT-12530)
[SUPPORT-13416](https://jira.linuxfoundation.org/browse/SUPPORT-13416)
Reporters: Bob Killen (Google LLC), FINOS
Organization: All
Project: All

Issue Summary:
The CLA Corporate Console displays the "date_modified" date from cla-prod-signatures table in DynamoDB to all the Approval Criteria Added On date, which is not accurate.

When a CLA Manager is added or removed from the Organization, the "date_modified" date changes and displays the same data for all the Approval Criteria options.

For Google LLC Organization scenario, the last change was on August 19 2022:

This change modified the "date_modified" date and now all the Approval Criteria for the Organization is showing the same Added On date.

https://jira.linuxfoundation.org/browse/LFX-3194

Observe difference in this section of approval list
![image](https://user-images.githubusercontent.com/46732999/216713656-a5a6f266-f129-4fd2-b8d5-b5f938912dac.png)

vs Event log
![image](https://user-images.githubusercontent.com/46732999/216713899-e6d6f8dd-0124-4b94-a4b6-fa89289c78f7.png)

**Comment by WillsonHG** [comment]
Hello @mrbobbytables I created this to publicize the issue you and others have raised about the dates in the Approval list being incorrect. The team is investigating the issue and will come back with an ETA or a fix soon.

**Comment by mlehotskylf** [comment]
We've discussed this internally, and we're committed to resolving it promptly. However, EasyCLA currently can't accurately track the timestamp for corporate contributor additions. We have a proposed solution that requires performance testing. We're finalizing our next release in the next couple weeks and we would like to address this issue in following releases. Unfortunately, I can't provide an exact ETA until we complete evaluation of our proposed solution. 

If you urgently require access to the dates when individual contributors were added, we are more than willing to perform a one-time manual export from our database within a short timeframe to assist you.

**Comment by mrbobbytables** [comment]
No worries @mlehotskylf it's not urgent. I appreciate you looking into it 👍

**Comment by mlehotskylf** [comment]
Correct, @krook. The date isn't lost; it's stored in our "event log" within the DynamoDB table. Currently, the UI doesn't display this date; instead, it shows the update date for the organization's CCLA. We need to figure out an efficient method to access or track this date so that we can display it accurately and efficiently in the UI.

**Comment by mlehotskylf** [comment]
This is related to Jira UI ticket CD-2367 where UI changes needs to be implemented.

**Comment by nickmango** [comment]
Moving this to QA as verified in CD-2367

**Comment by thakurveerendras** [comment]
The existing approval list record is not visible at corporate cla page
![image](https://github.com/communitybridge/easycla/assets/75417507/81078951-4c37-45c6-95fc-cc0f331e4ae4)

**Comment by nickmango** [comment]
This was a UI issue that has been resolved. Kindly reverify @thakurveerendras

**Comment by mlehotskylf** [comment]
@nickmango to confirm if this is BE or UI issue.

**Comment by mlehotskylf** [comment]
This is BE issue and @nickmango will create PR soon.

**Comment by nickmango** [comment]
Added indexing and resolved the child project events fetched. @thakurveerendras  kindly review

**Comment by thakurveerendras** [comment]
Tested issue on reported child project and found that it is fixed as expected
![image](https://github.com/communitybridge/easycla/assets/75417507/e0f24586-fad0-40cc-91fb-69adae36b098)

**Comment by thakurveerendras** [comment]
Blank approval list records appear after deployment, So reopening this ticket  
![image](https://github.com/communitybridge/easycla/assets/75417507/a15c3007-027a-477a-8898-5f5af73a8e7f)

**Comment by nickmango** [comment]
@thakurveerendras  This is a UI deployment issue not yet resolved

**Comment by nickmango** [comment]
Deployment and infra changes have been completed. @thakurveerendras kindly verify

**Comment by mlehotskylf** [comment]
We are improving performance for this solution so moving back to progress.

**Comment by krook** [comment]
@mlehotskylf do we know if this issue is planned for deployment soon?

**Comment by mlehotskylf** [comment]
Hi @krook. This fix is in progress and our goal is to fix this in next major release (in next few weeks or so).

**Comment by thakurveerendras** [comment]
@nickmango Retested the issue on the dev site and found that the Approved List date is still not accurate
![image](https://github.com/communitybridge/easycla/assets/75417507/848b13f9-d031-4166-b7ed-9a2f19585042)

**Comment by thakurveerendras** [comment]
Retested on the dev site and found that for some records still wrong date & time appear, 
Refer to the screenshot
![image](https://github.com/communitybridge/easycla/assets/75417507/4f665163-f127-49a7-b430-7cf709f2742b)

**Comment by thakurveerendras** [comment]
Tested on dev site & found that records **date & time** are proper & expected. So updating this ticket status

**Comment by thakurveerendras** [comment]
Issue is still reproducible on prod, So reopening this issue 
![image](https://github.com/communitybridge/easycla/assets/75417507/44f1ac97-3c33-411e-8357-072df076993f)

**Comment by nickmango** [comment]
@thakurveerendras kindly reverify.. A migration was still running in prod

**Comment by mlehotskylf** [comment]
Yes @krook, we resolved the issue last week and have recently completed updating the `Added On` date for contributors across all projects and organizations. However, please note that if a contributor was added to the "approval list" before August 2022, the `Added On` date might not be accurate. This inaccuracy stems from our migration from version V1 to version V2, where V1 did not closely track this date.

Closing this ticket.
