### ISSUE TITLE
CLA Corporate Console Activity Log shows data from other organizations and 

### ISSUE THREAD

**Issue by jarias-lfx** [communitybridge/easycla#3817]
## Summary

The CLA Corporate Console https://organization.lfx.linuxfoundation.org/ Activity Log in the Child project when there is an already created CLA Group in the parent project is showing data from the parent CLA Group and in the child CLA Group is showing data from other organizations. While the parent CLA Group can see the child CLA Group data from the same organization is not considered a critical situation. Seeing data from other organizations is a critical issue.

## Background

To reproduce this in PROD.
1- Access the CLA Corporate Console https://organization.lfx.linuxfoundation.org/ 
2- Search for FDC3 FINOS Child CLA Group
3- The page loads Activity Log from other organizations (see below screenshots)

## Expected behavior

1- When selecting the parent CLA Group the activity log should only be for the parent CLA Group
2- When selecting the child CLA Group, only the activity log from the child CLA Group and from your organization should be displayed

## Screenshots

From Test_NDC organization (Note The Linux Foundation activity log is being displayed)
![image](https://user-images.githubusercontent.com/93140557/221633409-2aebbb3b-11b4-4893-bb60-84972238cd30.png)

From The Linux Foundation organization (Note Test_NDC activity log is being displayed)
![image](https://user-images.githubusercontent.com/93140557/221634123-ff21b0ec-42cd-483e-ab7f-ad299bc91b7e.png)

## Environment

* Environment:
  - [ ] ALL
  - [ ] DEV
  - [ ] STAGING
  - [x] PROD 
* Browser:
  - [x] Chrome/Brave
  - [ ] Firefox
  - [ ] Opera
  - [ ] Vivaldi
  - [ ] LibreWolf
  - [ ] SRware Iron
  - [ ] Dissenter
  - [ ] Slimjet
  - [ ] Midori
  - [ ] Edge
  - [ ] Lynx

**Comment by dealako** [comment]
Deployed to DEV and PROD. @WillsonHG, @thakurveerendras, and @jarias-lfx can you confirm the fix is also resolved in PROD?

**Comment by thakurveerendras** [comment]
Hello @dealako , @nickmango 
Tested issue on dev site & found that it is still reproducible as reported ,

Kindly find details 

- Project Name : SUN 
- Link : https://lfx.dev.platform.linuxfoundation.org/foundation/a092h000004x5tVAAQ/cla

- User 1 :  vthakur | organization :Infosys limited 
- User 2 : veerendrat | organization : Microsoft corporation 

![image](https://user-images.githubusercontent.com/75417507/222052043-8e39be30-0a36-43e4-a05a-19c724f438d2.png)

**Comment by jarias-lfx** [comment]
Confirmed the issue has been fixed in PROD. Only the current organization information is showing in the CLA Corporate Console.
![image](https://user-images.githubusercontent.com/93140557/222164228-4081baa9-93fb-4f19-a770-f30d9d6a4141.png)

**Comment by jarias-lfx** [comment]
Also confirmed the Activity log from the parent project CLA Group is only displaying the activity log information from the project CLA Group.
![image](https://user-images.githubusercontent.com/93140557/222164651-b58b7a3a-c37b-4880-8f30-ab43c157eb01.png)

**Comment by thakurveerendras** [comment]
Confirmed issue is also fixed as expected on dev environment
![image](https://user-images.githubusercontent.com/75417507/222187776-cb854241-6a9e-4bae-951f-8677700f7067.png)
