### ISSUE TITLE
EasyCLA Employee Acknowledgments - Create/Invalidate/Create/Invalidate/Create Issue

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#3824]
## Summary

EasyCLA Employee Acknowledgments - Create/Invalidate/Create/Invalidate/Create Issue

## Background

While testing the EasyCLA auto-create employee acknowledgments, it was discovered that the GitHub Pull Requests would fail authorization under certain conditions.

Scenario:

1. The CLA Manager enables auto-create employee acknowledgments for a given CLA Group and Project for their company.
2. The CLA Manager adds a user to the authorization list by email, GitHub username, or GitLab username
3. The CLA Manager observes the user is authorized in the Employee Acknowledgment table on the CLA Corporate Console
4. The CLA Manager later decides to invalidate the user by removing them from the approval list
5. The CLA Manager observes the user is no longer authorized in the Employee Acknowledgment table on the CLA Corporate Console
6. The CLA Manager adds the same user to the authorization list by email, GitHub username, or GitLab username
7. The CLA Manager observes the user is authorized in the Employee Acknowledgment table on the CLA Corporate Console
8. The CLA Manager later decides to invalidate the user by removing them from the approval list
9. The CLA Manager observes the user is no longer authorized in the Employee Acknowledgment table on the CLA Corporate Console
10. The CLA Manager adds the same user to the authorization list by email, GitHub username, or GitLab username
11. The user tests authorization by creating a Pull request and observes they are not authorized.

## Discussion

This is likely due to how we process the employee acknowledgments on the GitHub checks/authorization side. In the above scenario, we create the initial employee authorization and then disable it by setting the approved flag to false.  Later, when the user is re-authorized, we create a new employee acknowledgment record - the old record remains unchanged.  This new employee acknowledgment shows the user as authorized.   When the GitHub CLA check occurs, we discover two records. The authorization logic probably only reviews the first record and not the second.  @nickmango is reviewing the logic and will update the code to consider all CLA Group/Company/User employee acknowledgments.

## Expected behavior

Authorization should work.

## Screenshots

Engineering discussion notes:

<img width="1118" alt="Screenshot 2023-03-01 at 10 28 06 AM" src="https://user-images.githubusercontent.com/519609/222229802-5e0db022-ae79-4616-bb7a-76cf529a1f1e.png">

**Comment by nickmango** [comment]
@dealako on investigation discovered the Github PR checks work as expected. The user list query checks all users and gets one with signed and approved set to true. 
GitLab checks need an update as these arent working as expected . Confirmed with @thakurveerendras Gitlab is still a fail and github a pass
cc @thakurveerendras

**Comment by thakurveerendras** [comment]
Issue is still reproducible with below steps 
Create GitHub PR (Easycla gated) : https://github.com/Sun-lfxfoundationOrgTest/Repo01/pull/1
Login company portal  
Add GitHub user under approval list 
Go to postman & enable autoCreateECLA
Refresh company portal & GitHub PR

Actual results  :  [thakurveerendras] user added under contributor ack list bur PR remain Not covered 
Refer screenshot : 
![image](https://user-images.githubusercontent.com/75417507/224543835-23c2e47f-dee3-4f55-bfeb-53476ac778c1.png)
![image](https://user-images.githubusercontent.com/75417507/224543881-fe4b2295-6041-4bf7-9985-eb8b328d1207.png)

**Comment by nickmango** [comment]
@thakurveerendras I tested and this was working as expected. I added , removed a couple of times and user was passed and gated respectively. 
Kindly reverify. You can check after the user has been successfully added to the approval list . It takes a couple of seconds to update 

https://github.com/Sun-lfxfoundationOrgTest/Repo01/pull/2

**Comment by thakurveerendras** [comment]
@nickmango , Issue is still reproducible as reported yesterday 
Kindly refer video steps for more details 
https://images.zenhubusercontent.com/194341141/21a4f98a-297c-4ae5-b8c9-b5956e19d41e/3824.mp4

**Comment by umeshlumbhani247** [comment]
@thakurveerendras 
Can you please check it again, On my side, it is working fine.

**Comment by thakurveerendras** [comment]
Tested issue on dev site & found that with GitHub user name it is working fine but not working with contributors email address
Refer video clip :  
[contributors email.webm](https://github.com/communitybridge/easycla/assets/75417507/aa6602ee-9d2f-45a0-b212-715e16aa59e2)

**Comment by umeshlumbhani247** [comment]
@thakurveerendras 
Can you please review again ? As i think this issue has been fixed, and it's working on my side with the same email and git account added by you in video clip.

**Comment by thakurveerendras** [comment]
@umeshlumbhani247 , Issue is still reproducible as describe above 
### Refer steps :
1. Create cla gated  PR : https://github.com/SunEarthChildOrg/devRepo01/pull/2
2. Add GitHub username under approval list 
3. See-Easycla PR will covered
4. Delete GitHub user from approval list 
5. See- Easycla PR updated Not Covered 
6. Now add Github user email address under approval list 

### Actual results :
1. PR remain Not Covered
2. Two records created at contributor list 
![image](https://github.com/communitybridge/easycla/assets/75417507/8cfd2de6-7a5a-4993-93f5-c91a95cdc44b)

**Comment by nickmango** [comment]
Related #3910 and #3870
