### ISSUE TITLE
GitLab MR remain not covered when GitLab user added under approval list & contributor list (Auto-ECLA)

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3870]
- Precondition : Auto-ECLA should enabled for project
- Project URL : https://organization.lfx.linuxfoundation.org/foundation/null/project/a092M00001IdwOGQAZ/cla

Steps :

1. Create Merge Request on GitLab : https://gitlab.com/jarias-lfx-test1/jarias-lfx-testproject1/-/merge_requests/8
2. See-MR is gated
3. Login CD cla portal
4. Add GitLab user under approval list 
5. See-User automatic added under contributor list 
6. Go to GitLab & Refresh MR 

Actual results : GitLab MR remain not covered when GitLab user added under approval list & contributor list (Auto-ECLA)
Refer video clip :
https://images.zenhubusercontent.com/194341141/274fe951-f86a-45fa-a110-e929759464ae/autoecla.mp4

**Comment by umeshlumbhani247** [comment]
Investigation is done, It seems when user added under approval list, realtime update of MR is not implemented for gitlab. 
I am working on it.
CC: @mlehotskylf , @thakurveerendras

**Comment by umeshlumbhani247** [comment]
@mlehotskylf 
Done with fix, found another issue
Investigating on another issue, while adding "/easycla" command, MR is not updated with latest record.
Also when adding gitlab user with same email, it was creating separate user and signature instead of existing one.
Investigated with @nickmango

**Comment by thakurveerendras** [comment]
Hello @umeshlumbhani247 
Issue is still reproducible as reported on dev site, 

- Refer user : thakurveerendras1
- Kindly review MR : https://gitlab.com/gitlabcommenttest/repo/-/merge_requests/8
- Refer video clip : 

[3870.webm](https://github.com/communitybridge/easycla/assets/75417507/16da325f-9866-473f-8a59-74e4f9a5761c)

**Comment by thakurveerendras** [comment]
Same behaviour with GitLab contributors email 
Email address : vthakur@contractor.linuxfoundation.org
MR : https://gitlab.com/gitlabcommenttest/repo/-/merge_requests/9

**Comment by umeshlumbhani247** [comment]
@thakurveerendras 
Deployment was failed, It has been resolved on dev.
Please review from your side.

**Comment by thakurveerendras** [comment]
Testing is blocked due to new issue #3996

**Comment by thakurveerendras** [comment]
Hello @umeshlumbhani247 

- Issue is still reproducible as reopened , Kindly refer user details below 

GitLab User : veerendrat
Email address : [vthakur@contractor.linuxfoundation.org](mailto:vthakur@contractor.linuxfoundation.org)
MR : https://gitlab.com/gitlabcommenttest/repo/-/merge_requests/9

**Comment by thakurveerendras** [comment]
Tested issue with below user & found that it is working fine, Now GitLab MR covered when GitLab user added under approval list & then add /easycla comment 

- GitLab user:  vthakur.lflegal
- Email address : [vthakur+lflegal@contractor.linuxfoundation.org](mailto:vthakur+lflegal@contractor.linuxfoundation.org)

**Comment by thakurveerendras** [comment]
Tested issue on prod & found that MR properly covered when user added /easycla comment after add GitLab user under approval list

- GitLab user: vthakur.lflegal
- Email address : [vthakur+lflegal@contractor.linuxfoundation.org](mailto:vthakur+lflegal@contractor.linuxfoundation.org)
- MR : https://gitlab.com/clagitlab_v_lflegal/project01/-/merge_requests/1

![image](https://github.com/communitybridge/easycla/assets/75417507/bd4dae3a-53c0-4434-9d81-6929118eb166)

**Comment by mlehotskylf** [comment]
This is done, closing.
