### ISSUE TITLE
Ecla process remain incomplete after invalided signature 

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3897]
Related issue : [PCC-2866](https://jira.linuxfoundation.org/browse/PCC-2866)

## Summary

Ecla process remain incomplete after invalided signature 

## Steps

1. Login admin portal
2. Add Cla group & cla enforced GitLab group 
3. Create GitLab MR 
4. Now click on Not covered 
5. Singed ECLA 
6.  See-ICLA records created at PCC signature table 
7. Invalidate ICAL records
8. Go to GitLab MR & try to again signed ecla
9. See-You are done appears & user redirect to MR after click on exist 
10. Go to PCC signature table

Actual results : Singed ICLAs records remain invalidate with Incomplete stage

## Expected behavior

After step 8 , user should redirect to doc-sign (ICLA)

## Screenshots

https://user-images.githubusercontent.com/75417507/232020119-4b08327d-f74c-445c-b20b-b62756ece04e.mp4

**Comment by umeshlumbhani247** [comment]
@thakurveerendras 
This issue has been resolved.
CC: @mlehotskylf

**Comment by mlehotskylf** [comment]
@thakurveerendras can you please confirmed this has been tested? If yes then please change the status. Thanks!

**Comment by thakurveerendras** [comment]
Issue is still reproducible as reported on dev site, 
Kindly refer to the video clip:[3897.webm](https://github.com/communitybridge/easycla/assets/75417507/c2d29471-ddad-4fbc-9055-a4b9eb705907)

**Comment by nickmango** [comment]
@thakurveerendras let us touch base and verify this as from my investigation this could be reproducible in prod and is not a regression issue.

**Comment by mlehotskylf** [comment]
@thakurveerendras to check in PROD if this is regression issue. If it is nor regression we will not fix it in this release (v2.0.150).

**Comment by thakurveerendras** [comment]
Tested issue on Prod & found that it is not reproducible, So it is a regression bug
Refer to the video clip: [3897_Reg.webm](https://github.com/communitybridge/easycla/assets/75417507/4de37884-8214-4d5f-928a-428391a58f41)

**Comment by thakurveerendras** [comment]
Tested the issue with GitLab Mr and found that it is not reproducible as reported. So making issue status Done at dev site
![image](https://github.com/communitybridge/easycla/assets/75417507/68d3a930-1a54-4afd-a497-dbd390f79d11)

**Comment by thakurveerendras** [comment]
Not reproducible on prod, So closing this issue
