### ISSUE TITLE
User is redirected to the respective home page when clicked on Linux Foundation logo in menu bar

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#621]
## Background
1. Launch Project Management Console in dev environment
2. Login as Project Manager
3. Click on The Linux Foundation logo from menu bar
4. Observed user is redirected to All Projects page
NOTE: Observed user is redirected to All Companies page in Corporate console

## Expected Behavior
User should be redirected to Linux Foundation home page or link should be remove for the logo as we already have link for All Projects page in menu bar

**Comment by dealako** [comment]
@nirupamav please confirm this was fixed.

**Comment by nirupamav** [comment]
@dealako 
I cleared the cache and verified the issue but looks like the issue is still not fixed

**Comment by nirupamav** [comment]
Verified that user is redirected to Linux Foundation homepage when clicked on the logo from menu bar
Verified in Chrome, Firefox and IE
**Project Management Console**
![image](https://user-images.githubusercontent.com/60865903/76063004-d02f5d00-5fac-11ea-9663-1839c4789895.png)

**Corporate Console**
![image](https://user-images.githubusercontent.com/60865903/76063088-02d95580-5fad-11ea-8ee8-a9adcdf2d8c3.png)
